# Generated by Django 4.2.3 on 2023-08-07 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_booking_no_of_guests_alter_menu_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='titte',
            new_name='title',
        ),
    ]
